
app = "Sapphire"

modules = [
	"filesystem"
]

[user]
name = "Haseeb"




[logger]
#configurations for the built-in logger module

logfile = "sapphire.log"
#relative to root directory, can use absolute paths.

level = "debug" 
# valid values: debug, info, warning, critical 

terminal = true
#whether to log into the terminal or not


[model]
#configurations for the model manager module
name = "gemini"
