
app = "Sapphire"

[user]
name = "Haseeb"




[logger]
#configurations for the built-in logger module

logfile = "sapphire.log"
#relative to root directory

level = "debug" 
# valid values: debug, info, warning, critical 

terminal = true
#whether to log into the terminal or not