
app = "Sapphire"

modules = [
	"filesystem"
]



[user]

name = "Haseeb"

dev = true
# Activates dev features which include:
# 1) Event logs
# 2) Error raising instead of suppressing in .handle() and the event loop.



[logger] #configurations for the built-in logger module

logfile = "sapphire.log"
#can use absolute paths.

level = "debug" 
# valid values: debug, info, warning, critical 

terminal = true
#whether to log into the terminal or not


[model]
#configurations for the model manager module
name = "gemini"

#dev note: see how the name corresponds to the sub-field down below.
#this is essential for proper config transfer

[model.gemini]

api_key = "load:secrets.txt"

# all model classes follow this scheme. 
# The api_key value can either be the literal api key OR
# you can use 'load:' prefix to load the key from a file.
# Obviously this does'nt apply for local models 

# api_key = "123abc" will also work


[prompt]
#configurations for the prompt manager
memory_length = 30
#amount of interactions between the AI and the user to keep. Each individual message takes 1 memory slot.


