
app = "Sapphire"

modules = [
	"filesystem"
]

[user]
name = "Haseeb"




[logger]
#configurations for the built-in logger module

logfile = "sapphire.log"
#relative to root directory, can use absolute paths.

level = "debug" 
# valid values: debug, info, warning, critical 

terminal = true
#whether to log into the terminal or not


[model]
#configurations for the model manager module

name = "gemini"
#see how the name corresponds to the sub-field down below.

[model.gemini]

api_key = "load:secrets.txt"

# all model classes follow this scheme. 
# The api_key value can either be the literal api _key OR
# you can use 'load:' prefix to load the key from a file. 

# api_key = "123abc" will also work