from typing import Any, Callable, Optional
from dataclasses import dataclass
from datetime import datetime
from typing import Literal, Union
import threading

from .chain import Chain


class HalogenEvents():
	"""
	All Halogen Events and helper functions.
	"""
	Chain = Chain
	_lock = threading.Lock()
	_intern_chain = Chain(0, 0)
	_current_context = 0
	_intern_map: dict[str, type["Event"]] = {}

	@classmethod
	def chain(cls, event: Union["Event", None] = None) -> Chain:
		"Class Method to chain events. If None, returns a new chain."
		if isinstance(event, cls.Event):
			return event.chain
		else:
			chain = cls._intern_chain
			with cls._lock: 
				cls._intern_chain = Chain(
					0,
					chain.flow + 1
				)
			return chain
		
		
	@classmethod
	def new_context_chain(cls) -> Chain:
		"Method for getting a chain with a new context. Should only be used by Halogen Server!"
		with cls._lock: cls._current_context += 1
		chain = Chain(
			cls._current_context, 0
		)
		return chain
	

	@classmethod
	def make_timestamp(cls):
		"Class method for giving a standard timestamp format for all events."
		return datetime.now().strftime("%H:%M:%S")
			
	
	@classmethod
	def serialize(cls, event: str) -> type["Event"]:
		"Method for getting an event class using its name. Will raise an exception on invalid values."

		if not cls._intern_map:
			for name, attr in HalogenEvents.__dict__.items():

				if not isinstance(attr, type): continue

				if issubclass(attr, HalogenEvents.Event):
					cls._intern_map[name] = attr

		if event not in cls._intern_map:
			raise ValueError(f"Unknown event: {event}")
		return cls._intern_map[event]
		


	@dataclass(frozen = True)
	class Event():
		"Base event class."
		sender: str
		timestamp: str 
		chain: Chain


	@dataclass(frozen = True)
	class InitCompleteEvent(Event):
		"An event passed just before the main loop starts."
		pass


	@dataclass(frozen = True)
	class LogEvent(Event):
		"Event that the logger module listens for."
		level: Literal["debug", "info", "warning", "critical"]
		message: str


	@dataclass(frozen = True)
	class ShutdownEvent(Event):
		"Sent to core to intiate a shutdown."
		emergency: bool
		reason: str = ""


	@dataclass(frozen = True)
	class RestartEvent(Event):
		"Sent to core to intiate a restart."
		reason: str = ""


	@dataclass(frozen = True)
	class CommandRegisterEvent(Event):
		"Sent to command handler to register a command"
		module: str
		cmd: str
		info: str
		func: Callable[[list[str], "HalogenEvents.Chain"], str]


	@dataclass(frozen = True)
	class CommandEvent(Event):
		"Command that the command handler can execute."
		module: str
		cmd: str
		args: list[str]


	@dataclass(frozen = True)
	class CommandExecutedEvent(Event):
		"The output of an executed command."
		cmd: tuple[str, str, list[str]]
		success: bool
		output: str


	@dataclass(frozen = True)
	class ConfirmationEvent(Event):
		"Used for confirmation with the user."
		message: str
		options: list[str]
		selected: str | None


	@dataclass(frozen = True)
	class ErrorEvent(Event):
		"In case something goes wrong."
		error: str

	@dataclass(frozen = True)
	class UserInputEvent(Event):
		"All user messages are sent using this event."
		message: str


	@dataclass(frozen = True)
	class NotifyEvent(Event):
		"Modules can use this event to send a message to the AI."
		message: str


	@dataclass(frozen = True)
	class PromptEvent(Event):
		"Event passed by the prompt manager after it assembles the prompt"
		content: str


	@dataclass(frozen = True)
	class AIResponseEvent(Event):
		"The response generated by the AI model."
		message: str
		extras: dict[str, Any]

	
	@dataclass(frozen = True)
	class ClientActivationEvent(Event):
		"The first event passed by the server to the client so it can initialize its chain."
		message: str

	
	@dataclass(frozen= True)
	class TaskRegisterEvent(Event):
		"Event passed to task manager to register an new task."
		namespace: str
		task_name: str
		args_info: list[str]
		info: str
		func: Callable[[list[str], Chain], str]


	@dataclass(frozen= True)
	class TaskRegisteredEvent(Event):
		namespace: str
		task_name: str
		args_info: list[str]
		info: str


	@dataclass(frozen= True)
	class _SubTask:
		namespace: str
		func_name: str
		args: list[str]

	@dataclass(frozen= True)
	class TaskEvent(Event):
		"Start a new task."
		name: str
		sub_tasks: list["_SubTask"]


	@dataclass(frozen= True)
	class _SubTaskCompletion:
		namespace: str
		func_name: str
		args: list[str]
		success: bool
		output: str

	@dataclass(frozen= True)
	class TaskCompletionEvent(Event):
		"The result of a task."
		name: str
		sub_tasks: list["_SubTaskCompletion"]


	

	
	


